#!/bin/sh

# exit on failure
set -e

# fail on unassigned variable
set -u

# remove systemd 'wants' triggers
find \
	/etc/systemd/system/*.wants/* \
	/lib/systemd/system/multi-user.target.wants/* \
	/lib/systemd/system/local-fs.target.wants/* \
	/lib/systemd/system/sockets.target.wants/*initctl* \
	! -type d \
	-delete

# remove everything except tmpfiles setup in sysinit target
find \
	/lib/systemd/system/sysinit.target.wants \
	! -type d \
	! -name '*systemd-tmpfiles-setup*' \
	-delete

# remove UTMP updater service
find \
	/lib/systemd \
	-name systemd-update-utmp-runlevel.service \
	-delete

# just for cosmetics, fix "not-found" entries while using "systemctl --all"
for MATCH in \
	plymouth-start.service \
	plymouth-quit-wait.service \
	syslog.socket \
	syslog.service \
	display-manager.service \
	systemd-sysusers.service \
	tmp.mount \
	systemd-udevd.service \
	; do
		grep -rn --binary-files=without-match  ${MATCH} /lib/systemd/ | cut -d: -f1 | xargs sed -ri 's/(.*=.*)'${MATCH}'(.*)/\1\2/'
done

systemctl disable ondemand.service
systemctl set-default multi-user.target

# cleanup build files
cd /
rm -rf /tmp/*
